import Foundation

enum CleanupCategory: String, CaseIterable, Identifiable {
    case systemCaches = "System Caches"
    case appLogs = "App Logs"
    case trash = "Trash"
    case browserCaches = "Browser Caches"
    case docker = "Docker"

    var id: String { rawValue }

    var icon: String {
        switch self {
        case .systemCaches: return "internaldrive"
        case .appLogs:      return "doc.text"
        case .trash:        return "trash"
        case .browserCaches: return "globe"
        case .docker:       return "shippingbox"
        }
    }

    var description: String {
        switch self {
        case .systemCaches:   return "Temporary files cached by macOS and apps"
        case .appLogs:        return "Log files generated by applications"
        case .trash:          return "Files waiting in the Trash"
        case .browserCaches:  return "Cached web content from browsers"
        case .docker:         return "Stopped containers, unused images & build cache"
        }
    }

    /// Filesystem paths to scan/clean for this category.
    /// Returns empty array for Docker (handled via CLI).
    var paths: [URL] {
        let home = FileManager.default.homeDirectoryForCurrentUser
        switch self {
        case .systemCaches:
            return [
                home.appendingPathComponent("Library/Caches")
            ]
        case .appLogs:
            return [
                home.appendingPathComponent("Library/Logs"),
                URL(fileURLWithPath: "/Library/Logs")
            ]
        case .trash:
            return [home.appendingPathComponent(".Trash")]
        case .browserCaches:
            return [
                home.appendingPathComponent("Library/Caches/com.apple.Safari"),
                home.appendingPathComponent("Library/Application Support/Google/Chrome/Default/Cache"),
                home.appendingPathComponent("Library/Caches/Firefox/Profiles"),
                home.appendingPathComponent("Library/Caches/com.google.Chrome")
            ]
        case .docker:
            return []
        }
    }

    var isDocker: Bool { self == .docker }
}
